### ISSUE TITLE
Needs option to add exceptions. 

### ISSUE THREAD

**Issue by hyperion032020** [focustense/FocusPatchers#3]
Certain mods do require those custom WNAM entries. For example: https://www.nexusmods.com/skyrimspecialedition/mods/48864 uses them to apply the minotaur mesh, I assume.

**Comment by focustense** [comment]
I don't really maintain this which is why it's nondiscoverable in the Synthesis Collective... but unless I'm misunderstanding the request, then this setting already exists, it's the `IgnoredModNames` ("Mods to ignore") setting. It won't touch records from any plugin in that list.
